/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Question2;

/**
 *
 * @author maxwe
 */

import java.util.*;
import java.io.*;
import javax.swing.*;
public class ProductForm extends javax.swing.JFrame {

    /**
     * Creates new form ProductForm
     */
   
    
    
    public ProductForm() {
        
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ULoadBtn = new javax.swing.JButton();
        USaveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReport = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        FileExitBtn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        LoadDataBtn = new javax.swing.JMenuItem();
        SaveDataBtn = new javax.swing.JMenuItem();
        EditClearBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ULoadBtn.setText("Load Product Data");
        ULoadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ULoadBtnActionPerformed(evt);
            }
        });

        USaveBtn.setText("Save Product Data");
        USaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USaveBtnActionPerformed(evt);
            }
        });

        txtReport.setColumns(20);
        txtReport.setRows(5);
        jScrollPane1.setViewportView(txtReport);

        jLabel1.setText("Years Processed:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                        .addComponent(USaveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ULoadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ULoadBtn)
                .addGap(32, 32, 32)
                .addComponent(USaveBtn)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        FileExitBtn.setText("Exit");
        jMenu1.add(FileExitBtn);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        LoadDataBtn.setText("Load Product Data");
        jMenu2.add(LoadDataBtn);

        SaveDataBtn.setText("Save Product Data");
        jMenu2.add(SaveDataBtn);

        EditClearBtn.setText("Clear");
        EditClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditClearBtnActionPerformed(evt);
            }
        });
        jMenu2.add(EditClearBtn);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ULoadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ULoadBtnActionPerformed
        // TODO add your handling code here:
        
        IProductSales ps = new ProductSales();
        int[][] salesData = ps.GetProductSales();
        
        StringBuilder sb = new StringBuilder();
        sb.append("PRODUCT SALES DATA\n");
        sb.append("==================\n\n");
        sb.append(String.format("%-15s %-12s %-12s %-12s\n", 
            "", "Microphone", "Speakers", "Mixing Desk"));
        sb.append(String.format("%-15s %-12s %-12s %-12s\n", 
            "", "---------", "--------", "-----------"));
        
        for (int i = 0; i < salesData.length; i++) {
            sb.append(String.format("Sales for year %d %-12d %-12d %-12d\n", 
                i + 1, salesData[i][0], salesData[i][1], salesData[i][2]));
        }
        
        txtReport.setText(sb.toString());
        
        // Update results
        
    

        int totalSales = ps.GetTotalSales();
        double averageSales = ps.GetAverageSales();
        int salesOverLimit = ps.GetSalesOverLimit();
        int salesUnderLimit = ps.GetSalesUnderLimit();
        int yearsProcessed = ps.GetProduct3Processed();
        
        txtReport.append("Total Sales: " + totalSales + "\n");
        txtReport.append(String.format("Average Sales: %.0f", averageSales) + "\n");
        txtReport.append("Sales over limit: " + salesOverLimit + "\n");
        txtReport.append("Sales under limit: " + salesUnderLimit + "\n");
        txtReport.append("Years Processed: " + yearsProcessed + "\n");
    
    }//GEN-LAST:event_ULoadBtnActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void EditClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditClearBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EditClearBtnActionPerformed

    private void USaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USaveBtnActionPerformed
        String report = txtReport.getText();
        
        

        try (FileWriter writer = new FileWriter("report.txt")) 
        {      
            writer.write("DATA LOG\n");
            writer.write("********************************\n");
            writer.write(report);
            writer.write("********************************");
            
            JOptionPane.showMessageDialog(this, "Text saved successfully!");
        } catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this, "Error saving text: " + ex.getMessage());
        }
        

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String[] args) {
//        SwingUtilities.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new Question2.ProductForm().setVisible(true);
//            }
//        });
//    
    }//GEN-LAST:event_USaveBtnActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        txtReport.setText("");
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Question2.ProductForm().setVisible(true);
            }
        });
    
    }   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EditClearBtn;
    private javax.swing.JMenuItem FileExitBtn;
    private javax.swing.JMenuItem LoadDataBtn;
    private javax.swing.JMenuItem SaveDataBtn;
    private javax.swing.JButton ULoadBtn;
    private javax.swing.JButton USaveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtReport;
    // End of variables declaration//GEN-END:variables
}


